# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqrtApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqrtnumber',
            name='sqrt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
